# Generated by Django 5.2.1 on 2025-05-26 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CompetitionResult",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("competition", models.CharField(db_index=True, max_length=255)),
                ("room_id", models.CharField(max_length=255)),
                ("command_name", models.CharField(max_length=255)),
                ("user_name", models.CharField(max_length=255)),
                ("scenario", models.CharField(db_index=True, max_length=255)),
                ("flight_time", models.FloatField(db_index=True)),
                ("false_start", models.BooleanField(default=False)),
            ],
        ),
    ]
